---
name: Build and test original
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: List directory structure
        run: ls -R
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"
      - name: Install dependencies
        run: yarn install
        working-directory: webapp
      - name: Lint code
        run: yarn lint
        #working-directory: webapp
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./webapp
          file: ./webapp/dockerfile
          tags: leduude/webapp:latest
