version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    # Define event triggers for the updates
    commit-message:
      prefix: "fix" # Example: customize commit message prefix
    on:
      push:
        branches:
          - main
